title: "Tezskin 사이트"
desc: "이 사이트는 Jekyll 의 테마를 제작해보는 연습용 사이트 입니다."
url: "https://github.com/teznote/tezskin"

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true