title: "Tezskin 사이트"
desc: "이 사이트는 Jekyll 의 테마를 제작해보는 연습용 사이트 입니다."
url: "https://github.com/teznote/tezskin"
cats:
- id: diary
  title: My Diary
  order: title
- id: study
  title: Programming Study
  order: asc
- id: web_develop
  title: Web Development
- id: test1
  title: Title Order
  order: title
- id: test2
  title: Title Desc Order
  order: title_desc
- id: test3
  title: Updated Order
  order: updated
- id: test4
  title: Updated Desc Order
  order: updated_desc

navtags:
- id: study
  title: Programming Study
  subs:
  - id: python
    title: Python
  - id: javascript
    title: Javascript
  - id: web
    title: Web Development
- id: diary
  title: My Diary
  subs:
  - id: todo
    title: To-do Lists
  - id: home
    title: Homework
    order: desc

permalink: /post/:title

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

future: true
